import "../styles/globals.css";
import Header from "./components/Header";
import Sidebar from "./components/Sidebar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body>
        <Header />
        <div className="w-full md:pl-14 py-5 flex">
          <Sidebar />
          <div className="w-full h-[88vh] overflow-y-auto px-5">{children}</div>
        </div>
      </body>
    </html>
  );
}
